controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    door_controller:
      type: joint_trajectory_controller/JointTrajectoryController

door_controller:
  ros__parameters:
    joints:
      - slide_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 25.0
    action_monitor_rate: 10.0

    constraints:
      goal_time: 1.0
      stopped_velocity_tolerance: 0.01
